### ISSUE TITLE
Doesn't run on Ubuntu 20.04.1 LTS with Discord installed via Flatpak

### ISSUE THREAD

**Issue by ghost** [janLuna/DiscordFetch#1]
When trying to run the Script(WITH PYTHON3) I get The Following Error:
```
maxi@maxi-ubuntu2004 DiscordFetch-master  ✗ python3 DiscordFetch.py
Couldn't find a logo for Ubuntu, tell me what distro you are using and i will add it!
My Discord: Totally Discord#8671

Traceback (most recent call last):
  File "DiscordFetch.py", line 25, in <module>
    rpc_obj = rpc.DiscordIpcClient.for_platform(client_id)
  File "/home/maxi/Schreibtisch/DiscordFetch-master/rpc.py", line 53, in for_platform
    return UnixDiscordIpcClient(client_id)
  File "/home/maxi/Schreibtisch/DiscordFetch-master/rpc.py", line 45, in __init__
    self._do_handshake()
  File "/home/maxi/Schreibtisch/DiscordFetch-master/rpc.py", line 60, in _do_handshake
    ret_op, ret_data = self.send_recv({'v': 1, 'client_id': self.client_id}, op=OP_HANDSHAKE)
  File "/home/maxi/Schreibtisch/DiscordFetch-master/rpc.py", line 108, in send_recv
    self.send(data, op)
  File "/home/maxi/Schreibtisch/DiscordFetch-master/rpc.py", line 116, in send
    self._write(header)
  File "/home/maxi/Schreibtisch/DiscordFetch-master/rpc.py", line 201, in _write
    self._sock.sendall(data)
OSError: [Errno 107] Transport endpoint is not connected
maxi@maxi-ubuntu2004 DiscordFetch-master  ✗ 
```

**Comment by hetvos** [comment]
i think the Rich Presence library isnt compatble with flatpak, i recommend youninstall Discord through the deb file/Debian package
