### ISSUE TITLE
Error while running on fedora

### ISSUE THREAD

**Issue by roxandtol** [janLuna/DiscordFetch#3]
```
$ python3 DiscordFetch.py
Traceback (most recent call last):
  File "/home/rodriguetos/Github-Repos/DiscordFetch/DiscordFetch.py", line 38, in <module>
    "large_image": getLogoID(),
  File "/home/rodriguetos/Github-Repos/DiscordFetch/DiscordFetch.py", line 18, in getLogoID
    if logo_id == "tux" and not no_logo_warning:
UnboundLocalError: local variable 'no_logo_warning' referenced before assignment
```
Already made sure i had stuff installed

**Comment by hetvos** [comment]
Try the latest version, should be fixed now!

**Comment by roxandtol** [comment]
Unfortunately nope
```
python3 DiscordFetch.py                                                                                                                                                                                      ░▒▓ ✔  at 15:23:55 
Traceback (most recent call last):
  File "/home/rodriguetos/Github-Repos/DiscordFetch/DiscordFetch.py", line 29, in <module>
    rpc_obj = rpc.DiscordIpcClient.for_platform(application_id)
  File "/home/rodriguetos/Github-Repos/DiscordFetch/rpc.py", line 53, in for_platform
    return UnixDiscordIpcClient(client_id)
  File "/home/rodriguetos/Github-Repos/DiscordFetch/rpc.py", line 45, in __init__
    self._do_handshake()
  File "/home/rodriguetos/Github-Repos/DiscordFetch/rpc.py", line 60, in _do_handshake
    ret_op, ret_data = self.send_recv({'v': 1, 'client_id': self.client_id}, op=OP_HANDSHAKE)
  File "/home/rodriguetos/Github-Repos/DiscordFetch/rpc.py", line 108, in send_recv
    self.send(data, op)
  File "/home/rodriguetos/Github-Repos/DiscordFetch/rpc.py", line 116, in send
    self._write(header)
  File "/home/rodriguetos/Github-Repos/DiscordFetch/rpc.py", line 201, in _write
    self._sock.sendall(data)
OSError: [Errno 107] Transport endpoint is not connected
```
